= JSON – úvod 

JSON: JavaScript Object Notation.
JSON je syntaxe pro ukládání a výměnu dat.
JSON používá syntaxi JavaScript, ale formát JSON je pouze text.
Text lze číst a použít jako datový formát libovolným programovacím jazykem.

== Pravidla syntaxe JSON
Syntaxe JSON je odvozena od syntaxe zápisu objektu JavaScript:
Data jsou ve dvojicích jmen / hodnot
Data jsou oddělena čárkami
Kudrnaté závorky drží objekty
Čtvercové závorky obsahují pole

== JSON používá JavaScript syntaxi
Protože syntaxe JSON je odvozena od zápisu objektu JavaScript, pro práci s JSON v JavaScriptu je potřeba jen velmi málo dalšího softwaru.
Pomocí JavaScriptu můžete vytvořit objekt a přiřadit mu data, například:

Příklad
`{jméno: "John", věk: 31, město: "New York"};`
K objektu JavaScript můžete přistupovat takto:

Příklad
// vrací Johna
`Jméno.osoby;`

Lze k němu také přistupovat takto:
Příklad
// vrací Johna
`osoba ["jméno"];`

== Pole JavaScriptu jako JSON
Stejným způsobem lze objekty JavaScriptu použít jako JSON, pole JavaScript lze také použít jako JSON.

V JSON musí být hodnoty jedním z následujících typů dat:
`Řetězec ( string )
číslo
objekt (objekt JSON)
pole ( array )
boolean
nula`
Hodnoty JSON nemohou být jedním z následujících typů dat:
`funkce
datum
nedefinováno`

Řetězce JSON
Řetězce v JSON musí být psány ve dvojitých uvozovkách.

Příklad
`{"name": "John"}
Čísla JSON
Čísla v JSON musí být celé číslo nebo pohyblivá čárka.`

Příklad
`{"age": 30}
Objekty JSON
Hodnoty v JSON mohou být objekty.`

Příklad
`{"zaměstnanec": {"jméno": "John", "věk": 30, "město": "New York"}}`
Objekty jako hodnoty v JSON musí dodržovat stejná pravidla jako objekty JSON.

== Objekty JSON
Syntaxe objektu
Příklad
`{"name": "John", "age": 30, "car": null}`
Objekty JSON jsou obklopeny složenými závorkami {}.
Objekty JSON jsou zapsány ve dvojicích klíč / hodnota.
Klíče musí být řetězce a hodnoty musí být platný datový typ JSON (řetězec, číslo, objekt, pole, boolean nebo null).
Klíče a hodnoty jsou odděleny dvojtečkou.
Každý pár klíč / hodnota je oddělen čárkou.

== Ukazkova aplikace

Novou aplikaci lze vytvořit spuštěním `npm run newapp` v základním adresáři SAGE2.
Všechny vlastnosti jsou volitelné a jsou nastaveny na výchozí hodnoty, pokud není uvedeno.
Příklad aplikace
Všechny aplikace potřebují minimálně složku obsahující dva soubory.
Vytvořte složku. V této složce vytvořte soubor.Do souboru přidejte následující:
----
{
  // Toto musí být název souboru skriptu
  "main_script": "helloWorld.js",
  // Šířka a výška, která se použije jako počáteční velikost aplikace při spuštění
  "width": 300,
  "lenght": 200,
  // Název, který se zobrazí v seznamu aplikací
  "title": "Hello World",
  // Volitelné ( nejsou povinné, ale jsou vhodné pro některé případy )
  "autor": "Gospoja Kobayashi <gospo@yandex.uk>",
  "license": "SAGE2-Software-Licence"
  //Nejčastější věcí, kterou musíte udělat ve schématu JSON, je omezit se na konkrétní typ. K tomu se používá klíčové slovo "type".
  "description": "A product in the catalog",
  "type": "object"
  // Závislosti jsou uvedeny v jednoduchém objektu, který mapuje název balíčku na rozsah verzí. Rozsah verzí je řetězec, který má jeden nebo více deskriptorů oddělených mezerami. Závislosti lze také identifikovat pomocí tarball nebo git URL.
  "dependencies": ["neco.js"],
  // Stačí ukázat soubor obsahující ikonu aplikace
  "icon": "obrazek.png",
  // Vhodné pro správu verze
  "version": "1.0.0",
  // Klíčové slova, vhodné pro vyhledovani souboru nebo aplikace
  "keywords": [ "notepad", "collaborative", "text" ],
  // Informace o formátech jiných souborů které se týká této applikace
  "fileTypes": [ "txt" ],
  // free nebo proportional. V závislosti na této proměně se mění konfigurace velikosti okna
  "resize": "free",
  // false/true. informuje o přítomnosti animace v aplikace
  "animation": false,
  // Pro ušetření informace o nahrátech souborech
  "load": {"value": 4},	
}
----
